### ISSUE TITLE
Part 2 - SDK Sample Java

### ISSUE THREAD

**Issue by mgroves** [couchbaselabs/workshop#27]
Create a Java sample of creating a document and executing a N1QL query.

This can be a simple console app.

* Create a "person" document: firstName, lastName, city, country, type="person". The fields can be populated with random strings/guids/etc.
* Create a N1QL query that selects all person documents and lists them.

(Every time the program is run, a new person document will be inserted and queried).

Please put the code in connect2016/developer/02/java

**Comment by daschl** [comment]
@mgroves can you provide more details of what exactly it should do, which dataset to use, what patterns to show etc? thanks! :)

**Comment by mgroves** [comment]
@subalakr this is great, and pretty much exactly what I wanted.

Would you mind changing the N1QL to get all person documents instead of just the one? So if the user runs it multiple times, it will keep building up documents, and I think it shows off N1QL a little better. I could probably hack on it myself, but I'm afraid Java doesn't like me very much :(

**Comment by mgroves** [comment]
Thank you!
