### ISSUE TITLE
Part 2 - SDK Sample PHP

### ISSUE THREAD

**Issue by mgroves** [couchbaselabs/workshop#28]
Create a PHP sample of creating a document and executing a N1QL query.

This can be a simple console app or a simple single web page, whatever is easier.

* Create a "person" document: firstName, lastName, city, country, type="person". The fields can be populated with random strings/guids/etc.
* Create a N1QL query that selects all person documents and lists them.

(Every time the program is run, a new person document will be inserted and queried).

Please put the code in connect2016/developer/02/php

**Comment by avsej** [comment]
implemented in #30
