### ISSUE TITLE
Part 3 - Full Stack code samples

### ISSUE THREAD

**Issue by mgroves** [couchbaselabs/workshop#32]
Part 3 of the workshop is a lab where users will build a full-stack application using Couchbase. This will be Angular2 -> REST API -> Couchbase.

A .NET, Node.js, and Java backend need to be built (and I will not turn away PHP code :)

The Angular2 piece will be (mostly) identical between each technology, so you don't need to worry about writing that portion (with one caveat).

For more detailed specs, see the text file here: https://github.com/couchbaselabs/workshop/blob/master/connect2016/developer/03/LabPart03Specs.txt

If you are curious, you can also see a full Angular sample here: https://github.com/couchbaselabs/restful-angularjs-nodejs

Please put your example code in the folder: developer/03/dotnet (or developer/03/node, developer/03/java, etc).

**Comment by MikeGoldsmith** [comment]
Hey Matt

Just looked at the REST API spec and I'd like suggest that we use a more normalised REST API structure (like below).

| Verb | URL | Description |
| --- | --- | --- |
| GET | api/person | Gets all person documents |
| GET | api/person/{id} | Get a person document by ID |
| POST | api/person | Create new person document |
| DELETE | api/person/{id} | Deleted person document with ID |

I think it's much clearer if you use the VERB as the intended action and include the resource (person) in the path.

If you agree I can have the .NET version done in an hour or two.

PS - This is very similar to what our current Sprint contains where we're updating the Travel Sample App with a standardised Angular 2 [try-front-end](https://github.com/couchbaselabs/try-cb-frontend) with each language creating it's own backend API (for example [try-cb-java](https://github.com/couchbaselabs/try-cb-java) & [try-cb-nodejs](https://github.com/couchbaselabs/try-cb-nodejs)). I've been working on the .NET one over the past few days. I understand this API is slightly different as you'll be delivering this content in a classroom environment.

PPS - If you need help generating the same content for Java / NodeJS, I can help build those too.

**Comment by mgroves** [comment]
This would require me to make changes to the Angular 2 code, which I was hoping to avoid. I agree that it's probably a better design for a real app, but for demo code I think it's sufficient.

**Comment by MikeGoldsmith** [comment]
Sure, I understand. I'll try to get the .NET version done soon.

**Comment by mgroves** [comment]
I just committed the Angular 2 code. I got it working with the .NET backend (after a few tweaks on both sides). Next, I will be testing with java and node, just to make sure everyone fits together.

**Comment by mgroves** [comment]
I need CORS enabled on these endpoints so that angular can access them while running on another port (or another site, hypothetically)
